models:
  GMA:
    config:
      epsilon: 1e-8
      num_heads: 1
      small: false
      mixed_precision: true
      alternate_correlation: false
      position_only: false
      position_and_content: false
    weights_path: "models/_pretrained_weights/raft-sintel.pth"
    other_args: {}

  RAFT:
    config:
      epsilon: 1e-8
      small: false
      mixed_precision: false
      alternate_correlation: false
    weights_path: "models/_pretrained_weights/raft-sintel.pth"
    other_args: {}

  PWCNet:
    weights_path: "models/_pretrained_weights/pwc_net_chairs.pth.tar"
    correlationSamplerOnlyCPU: false
    useCPU: false
    other_args: {}

  SpyNet:
    weights_path: "models/_pretrained_weights/spynet_weights.pth"
    other_args: {}

  FlowNet2:
    config:
      fp16: false
      rgb_max: 255.0
    weights_path: "models/_pretrained_weights/FlowNet2_checkpoint.pth.tar"
    other_args: {}
  MeFlow:
    config:
      downsample_factor: 8
      feature_channels: 128
      corr_radius: 4
      hidden_dim: 128
      context_dim: 128
      gamma: 0.8  # Exponential weighting

      mixed_precision: false

      # Distributed training
      local_rank: 0,

      # Misc
      count_time: False,
    weights_path: "models/_pretrained_weights/sintel.pth"
    other_args: {}
